In [2]:
#map syntax: map(function,iterable1,iterable2,.....)

def mul(a):
    return a*a
l=map(mul,[1,2,3])
print(list(l))

[1, 4, 9]


In [5]:
#i/p:ul=['ram','sita']
#o/p:['RAM','SITA']

def cap(a):
    return str.upper(a)
l=map(cap,["ram","sita"])
print(list(l))

['RAM', 'SITA']


In [7]:
#map with lambda
sum=map(lambda a:a**3,range(1,10))
print(list(sum))

[1, 8, 27, 64, 125, 216, 343, 512, 729]


In [2]:
#filter
b=list(filter(lambda x:x>=5,range(11,20)))
print(b)

[11, 12, 13, 14, 15, 16, 17, 18, 19]


In [6]:
#reduce with lamba

from functools import reduce
sum1=reduce(lambda a,b:a+b,range(0,10))
print(sum1)

45


In [7]:
import numpy as np
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [9]:
import numpy as np
ar=np.array("I am new to programming".split())
print(ar)# rpw matrix

['I' 'am' 'new' 'to' 'programming']


In [10]:
t=np.array([[1],[2],[3],[4]])
print(11)

11


In [11]:
l1=np.array([(1,2),(4,6),("janu",'bhagi')])
print(l1)

[['1' '2']
 ['4' '6']
 ['janu' 'bhagi']]


In [12]:
r=np.array(range(10))
r

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

range(up,range(lw,up),(range,lw,up,step)

# pandas
 

In [ ]:
--pip install pandas

In [1]:
import pandas

In [13]:
r2=np.array(range(4,13))
print(r2)



[ 4  5  6  7  8  9 10 11 12]


In [14]:
r=np.random.randint(10)
print(r)
r2=np.random.randint(10,40)
print(r2)
r3=np.random.randint(10,40,6)
print(r3)
r4=np.random.randint(10,100,(2,4))
print(r4)
r5=np.random.randint(10)
print(r5)

3
36
[30 10 39 35 33 11]
[[97 65 83 35]
 [31 76 13 85]]
1


In [15]:
#using linespace

print(np.linspace(10,20,5))
print(np.linspace(3,9,4))

[10.  12.5 15.  17.5 20. ]
[3. 5. 7. 9.]


In [16]:
11/5

2.2

In [17]:
for num in range(10,20,4):
    print(num)

10
14
18


In [18]:
10/5


2.0

In [19]:
fl=np.full((3,2),5)
print(f)
print('.....')
z.fill(9)
np.diag(st)

NameError: name 'f' is not defined

In [22]:
m=np.random.randint(30,60,(5,5))
print(m)

[[57 42 46 40 41]
 [58 36 30 53 37]
 [55 43 33 53 36]
 [54 36 31 36 46]
 [57 44 46 38 48]]


In [21]:
 ar

array(['I', 'am', 'new', 'to', 'programming'], dtype='<U11')

In [23]:
print(ar+m)
print('......')
print(m-ar)
print('......')
print(ar*m)
print('......')
print(m/ar)
print('......')


UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U11'), dtype('<U11')) -> dtype('<U11')

print(np.mean(m))
print(np.std(m))
print(np.median(ar))
print(np.dot(m))

In [30]:
np.log(0)

<ipython-input-30-f6e7c0610b57>:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [32]:
np.log(2)

0.6931471805599453

In [34]:
np.exp(2)

7.38905609893065

In [40]:
def greater(a,b):
    if a>b:
        return a
    else: return b
    
greater(4,10)

10

In [38]:
v=np.vectorize(greater)
print(v)

NameError: name 'pd' is not defined

In [39]:
dir(np.log)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__name__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'accumulate',
 'at',
 'identity',
 'nargs',
 'nin',
 'nout',
 'ntypes',
 'outer',
 'reduce',
 'reduceat',
 'signature',
 'types']

In [ ]:
import pandas

In [3]:
import pandas as pd

In [5]:
pd.__version__

'1.1.3'

In [7]:
s1 = 'hi hello good morning'.split()
pd.Series(s1)

0         hi
1      hello
2       good
3    morning
dtype: object

In [9]:
s = 'hello'
pd.Series(s)

0    hello
dtype: object

In [12]:
t = ('a','e','i','o','u')
pd.Series(t, index =['v1','v2','v3','v4','v5'])

v1    a
v2    e
v3    i
v4    o
v5    u
dtype: object

In [17]:
dic = {4:34,'key2':45,'key3':67}
pd.Series(dic)

4       34
key2    45
key3    67
dtype: int64

In [20]:
st = 'clear mam not understand'.split()
pd.DataFrame(st)

0
0       clear
1         mam
2         not
3  understand

In [3]:
import pandas as pd
st='i am not having any douts'.split()
pd.DataFrame(st)

0
0       i
1      am
2     not
3  having
4     any
5   douts

In [4]:
l=[[1,2,3],[4,5,6]]
pd.DataFrame(l)

0  1  2
0  1  2  3
1  4  5  6

In [7]:
d={'k1':'h','k2':'e','k3':'ui'}
pd.DataFrame(d,index= [1,2,3])

k1 k2  k3
1  h  e  ui
2  h  e  ui
3  h  e  ui

In [15]:
dic = {'Names':['Krishna','sunitha','buddy'],'marks':[45,65,78],'Id':[1,2,3]}
pd.DataFrame(dic, index = [1,2,3])

Names  marks  Id
1  Krishna     45   1
2  sunitha     65   2
3    buddy     78   3

In [9]:
d = {'key1':('a','y','r'),'key2':(6,4,3)}
pd.DataFrame(d,index = [1,2,3])

key1  key2
1    a     6
2    y     4
3    r     3

In [10]:
import numpy as np


In [12]:
s=pd.Series(np.random.randint(20,40,8))
s

0    23
1    34
2    33
3    20
4    26
5    37
6    37
7    39
dtype: int32

In [13]:
s[3:]

3    20
4    26
5    37
6    37
7    39
dtype: int32

In [16]:
s[5:7]

5    37
6    37
dtype: int32

In [17]:
s[1:6:2]

1    34
3    20
5    37
dtype: int32

In [20]:
    df1 =pd.DataFrame({'match':[2,3,4,5],'days':[34,67,85,23]},index=[2003,2004,2005,2007])
df1

match  days
2003      2    34
2004      3    67
2005      4    85
2007      5    23

In [27]:
   df1 = pd.DataFrame({ 'h_p':[9,0,4,7],'a_p':[3,5,6,7],'match':[2,3,4,5],'days':[34,67,85,23]},index=[2003,2004,2005,2007])
df1

h_p  a_p  match  days
2003    9    3      2    34
2004    0    5      3    67
2005    4    6      4    85
2007    7    7      5    23

In [24]:
dates = pd.date_range('2020-10-20','2020-10-25')
pd.Series(dates,index=['day1','day2','day3','day4','day5','day6'])

day1   2020-10-20
day2   2020-10-21
day3   2020-10-22
day4   2020-10-23
day5   2020-10-24
day6   2020-10-25
dtype: datetime64[ns]

In [30]:
marks_df = pd.read_csv('marks.csv')
marks_df

Name  Maths  Science  English  DS  DBMS
0    A    100       88       96  99    91
1    B     82       82       85  85    92
2    K     92       95       80  89    90
3    E     90       98      100  93    98
4    L     93       90       88  83    91
5    P     89      100       83  80    99
6    W     92       84       99  84    87
7    R     89       81       84  81   100
8    S     85       82       92  81    92
9    X     91      100       86  98    88

In [31]:
marks_df.tail()

Name  Maths  Science  English  DS  DBMS
5    P     89      100       83  80    99
6    W     92       84       99  84    87
7    R     89       81       84  81   100
8    S     85       82       92  81    92
9    X     91      100       86  98    88

In [32]:
marks_df.tail(4)

Name  Maths  Science  English  DS  DBMS
6    W     92       84       99  84    87
7    R     89       81       84  81   100
8    S     85       82       92  81    92
9    X     91      100       86  98    88

In [33]:
marks_df.describe()

Maths     Science    English         DS        DBMS
count   10.000000   10.000000   10.00000  10.000000   10.000000
mean    90.300000   90.000000   89.30000  87.300000   92.800000
std      4.808557    7.731609    7.04036   7.103207    4.589844
min     82.000000   81.000000   80.00000  80.000000   87.000000
25%     89.000000   82.500000   84.25000  81.500000   90.250000
50%     90.500000   89.000000   87.00000  84.500000   91.500000
75%     92.000000   97.250000   95.00000  92.000000   96.500000
max    100.000000  100.000000  100.00000  99.000000  100.000000

In [34]:
marks_df.dtypes

Name       object
Maths       int64
Science     int64
English     int64
DS          int64
DBMS        int64
dtype: object

In [38]:
marks_df.sort_values('Maths')

Name  Maths  Science  English  DS  DBMS
1    B     82       82       85  85    92
8    S     85       82       92  81    92
5    P     89      100       83  80    99
7    R     89       81       84  81   100
3    E     90       98      100  93    98
9    X     91      100       86  98    88
2    K     92       95       80  89    90
6    W     92       84       99  84    87
4    L     93       90       88  83    91
0    A    100       88       96  99    91

In [43]:
marks_df.sort_values('English')

Name  Maths  Science  English  DS  DBMS
2    K     92       95       80  89    90
5    P     89      100       83  80    99
7    R     89       81       84  81   100
1    B     82       82       85  85    92
9    X     91      100       86  98    88
4    L     93       90       88  83    91
8    S     85       82       92  81    92
0    A    100       88       96  99    91
6    W     92       84       99  84    87
3    E     90       98      100  93    98

In [39]:
marks_df.Maths.value_counts()

92     2
89     2
93     1
91     1
90     1
85     1
100    1
82     1
Name: Maths, dtype: int64

In [40]:
marks_df.isnull()

Name  Maths  Science  English     DS   DBMS
0  False  False    False    False  False  False
1  False  False    False    False  False  False
2  False  False    False    False  False  False
3  False  False    False    False  False  False
4  False  False    False    False  False  False
5  False  False    False    False  False  False
6  False  False    False    False  False  False
7  False  False    False    False  False  False
8  False  False    False    False  False  False
9  False  False    False    False  False  False

In [42]:
marks_df.dropna()

Name  Maths  Science  English  DS  DBMS
0    A    100       88       96  99    91
1    B     82       82       85  85    92
2    K     92       95       80  89    90
3    E     90       98      100  93    98
4    L     93       90       88  83    91
5    P     89      100       83  80    99
6    W     92       84       99  84    87
7    R     89       81       84  81   100
8    S     85       82       92  81    92
9    X     91      100       86  98    88